project_id = "nlajxquufrbfengvfyfp"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.openai-tts]
verify_jwt = false

[functions.script-chat]
verify_jwt = false

[functions.auto-dialog-cron]
verify_jwt = false
